# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.5.17.dev1+gf7bff9d.d20230605"
__version_tuple__ = version_tuple = (0, 5, 17, "dev1", "gf7bff9d.d20230605")
