# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.5.17.dev2+g942467a.d20230605"
__version_tuple__ = version_tuple = (0, 5, 17, "dev2", "g942467a.d20230605")
