# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.6.1.dev1+g73ea718.d20230605"
__version_tuple__ = version_tuple = (0, 6, 1, "dev1", "g73ea718.d20230605")
